# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10" 

python:
  install:
    - method: pip
      path: .
      # Optionally install with extras if needed for docs, e.g.:
      # extra_requirements:
      #   - docs   # installs k-diagram[docs]
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false