ignore:
  - "kdiagram/tests/*"
  - "kdiagram/datasets/data/*"
  - "kdiagram/datasets/_property.py"
  - "kdiagram/cli.py"
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%   # small wiggle room for PRs
