ignore:
  - "kdiagram/tests/*"
  # - "kdiagram/api/*"
  - "kdiagram/datasets/_property.py",   
  - "kdiagram/datasets/data/*"
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%   # small wiggle room for PRs
