# environment.yml (for k-diagram)
#
# Create:
#   conda env create -f environment.yml
# Activate:
#   conda activate k-diagram-dev
# Update:
#   conda env update -f environment.yml --prune
#
name: k-diagram-dev

channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python>=3.9

  # Runtime (from pyproject [project].dependencies)
  - numpydoc>=1.6
  - numpy>=1.25
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn

  # Testing / coverage
  - pytest>=8.0
  - pytest-xdist
  - pytest-cov
  - coverage

  # Dev utilities (match pyproject dev extras)
  - ruff>=0.4
  - black>=24.0

  # Misc / build helpers
  - pip
  - setuptools
  - wheel

  # Optional extras (nice-to-haves)
  - joblib
  - tqdm
  - pydantic

  # If you need heavy ML backends, keep them optional/commented:
  # - tensorflow
  # - pytorch
  # - jax
  
  # Docs toolchain (from docs requirements + pyproject dev)
  # Pip-only packages (especially Sphinx extensions)
  - pip:
    - sphinx>=7.0,<8.0
    - furo
    - sphinx-copybutton
    - myst-parser
    - sphinx-design
    - sphinx-gallery
    - sphinx-mathjax-offline  
    - sphinx-issues
    - sphinx-prompt
    
# (Intentionally NOT installing the package here via `pip -e .`;
# the workflow does `pip install . --no-deps` after the env is created.)
