# .github/workflows/python-package-conda.yml
name: Python Package (k-diagram)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniforge (Miniforge3)
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3  # Updated from Mambaforge
          miniforge-version: latest
          use-mamba: true
          activate-environment: k-diagram-dev
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          # NOTE: intentionally omit auto-activate-base to avoid alias warning

      - name: Show conda info
        run: |
          conda info
          conda list

      - name: Install k-diagram (no deps; conda handled them)
        run: |
          python -m pip install . --no-deps --force-reinstall

      - name:Lint (ruff and black)
        run: |
          echo "Checking for linter issues with Ruff..."
          ruff check .  # Checks for linting issues
          
          echo "Running Black to automatically fix formatting issues..."
          black .  # Automatically formats the code with Black

      - name: Test with pytest + coverage
        run: |
          echo "Running pytest with coverage..."
          pytest -n auto --cov=kdiagram --cov-report=xml --cov-report=term-missing tests/

      - name: Upload coverage to Codecov
        # Run unless it's a PR from a fork AND ensure a token is present
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # This is the correct way to reference secrets
          files: ./coverage.xml                 # default path from pytest-cov
          name: linux-py${{ matrix.python-version }}
          flags: unittests
          fail_ci_if_error: true

      - name: Print Debug Info on Failure
        if: failure()
        run: |
          echo "::group::Debug Information"
          echo "PATH=$PATH"
          conda info
          conda list
          echo "::endgroup::"
