# .github/workflows/python-package-conda.yml
# Workflow for k-diagram using Conda

name: Python Package using Conda (k-diagram)

# Trigger on pushes to main/develop and pull requests targeting main/develop
on:
  push:
    branches:
      - main
      - develop # Add other branches if needed
  pull_request:
    branches:
      - main
      - develop # Add other branches if needed

jobs:
  build-test-linux: # Renamed job for clarity
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} # Use login shell for conda activation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Use latest checkout action

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3 # Use latest setup action
      with:
        activate-environment: kdiagram-dev # Use the correct env name
        environment-file: environment.yml # Point to your env file
        python-version: "3.10" # Specify Python version (must be compatible with env file)
        auto-activate-base: false
        # Conda configuration options can be added here if needed later
        # channel-priority: strict

    - name: Install k-diagram package
      run: |
        python -m pip install . --no-deps --force-reinstall
        # --no-deps: Assume conda handled dependencies
        # --force-reinstall: Ensure local package overwrites any cached version

    - name: Lint with flake8
      run: |
        echo "Running flake8 linter..."
        # Max line length 88 is common (used by Black formatter)
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=12 --max-line-length=88 --statistics

    - name: Test with pytest and Generate Coverage
      run: |
        echo "Running pytest with coverage..."
        # Generate coverage report for the 'kdiagram' package
        # Save report as coverage.xml for Codecov uploader
        pytest --cov=kdiagram --cov-report=xml -n auto kdiagram/tests

    - name: Print Debug Info on Failure
      if: failure() # Only run if previous steps failed
      run: |
        echo "::group::Debug Information" # Group output in GitHub Actions UI
        echo "PATH=$PATH"
        echo "--- Conda Info ---"
        conda info
        echo "--- Conda List ---"
        conda list
        echo "::endgroup::"
